version: "3.2"
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  quickshot:
    build: .
    security_opt:
      - seccomp=./security/chrome.json
    ports:
      - 3000:3000
    links:
      - redis
    env_file:
      - .env.prod
